import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Provider from '@/components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Jobs',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className={inter.className}>
        <Provider>
          <div className='min-h-screen main-container bg-gray-50 flex flex-col'>
            {children}
          </div>
        </Provider>
      </body>
    </html >
  )
}
